Update mongo sample to koop 3.x with mongo updates
koopjs/koop-provider-mongo pull request #2
Opened 2017-03-15 22:55 UTC by phpmaps

@dmfenton @jgravois - let me know if this is any good for merging.  It's uses koop 3.5.0 and makes use of Mongo's [readable stream]([http://mongodb.github.io/node-mongodb-native/2.0/api/Cursor.html#stream).  Also connection details are in the config.

2017-03-15 23:15 UTC, dmfenton commented on mongo.js
> +      var collection = db.collection('restaurants')
this is a good place to generalize by using `req.params.id`

2017-03-15 23:16 UTC, dmfenton commented on mongo.js
> +        features.push(this.formatFeature(doc))
makes sense to translate the features as they come in, rather than waiting for the full batch

2017-03-15 23:17 UTC, dmfenton commented on mongo.js
> +        db.close()
I would close the DB connection immediately after the stream ends

2017-03-29 07:51 UTC, phpmaps commented
@dmfenton - ok changes made code review.

2017-03-30 20:05 UTC, dmfenton requested changes
just need to change one thing from what I can tell

2017-03-30 20:05 UTC, dmfenton commented on index.js
> +  disableIdParam: true,
this needs to be set to `false` or deleted

2023-10-27 23:18 UTC, rgwozdz commented
closing

2023-11-08 16:30 UTC, closed without merging